### ISSUE TITLE
Make f!paradox lolololol

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxOrigins/FelixBot#100]
kkkk going back to work on serious stuff dont hurt me :v

**Comment by Niputi** [comment]
Alright. Give me some irl pictures of you for that command

**Comment by ParadoxOrigins** [comment]
never. you already have a folder of all my pfp anyways >_>

**Comment by Niputi** [comment]
Nope. I don't have a folder of them. I only have emojis of them all

**Comment by ParadoxOrigins** [comment]
then download the emotes *shrug*

**Comment by Niputi** [comment]
not like cat. I don't wanna do it

**Comment by ParadoxOrigins** [comment]
thonk
